// Example of array variables not object
// Copyright 2023
#include <iostream>

using std::cout;
using std::endl;

void fillArrayRandom( int arr[], int length);
void printArray(int array[], int length);

int main() {
    int a[100];

    fillArrayRandom(a, 100);
    printArray(a, 100);
    return 0;
}

void fillArrayRandom( int arr[], int length) {
     std::random_device rd;  // a seed source for the random number engine
    std::mt19937 gen(rd()); // mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> distrib(1, 10);
 
    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 10]
    for (int n = 0; n != length; ++n)
        arr[n] = distrib(gen);
    std::cout << '\n';

}

void printArray(int array[], int length) {
   for (int i = 0; i < length; i++) {
      cout << array[i] << " ";
   }
   cout << endl;

}